import { GoogleGenAI } from "@google/genai";

// Standard articles template for offline mode
const DEFAULT_ARTICLES = [
  {
    id: "art_1",
    title: "Behavioral Friction: Designing Systems for High Compliance",
    category: "psychology",
    readTime: "4 min",
    summary: "Traditional habit builders focus on raw willpower. We explore why eliminating environmental friction outperforms determination in the long-term.",
    content: "Willpower is a depleting reservoir... By placing water bottles, resistance bands, and focused workspaces in physical paths, we create cues that initiate automated performance without energy depletion."
  },
  {
    id: "art_2",
    title: "Nutrition Architectures: Protein Satiety Explained",
    category: "nutrition",
    readTime: "3 min",
    summary: "Understanding the hormonal feedback loops of proteins vs simple carbohydrates in calorie restriction regimes.",
    content: "Proteins trigger high postprandial thermogenesis and stimulate peptide YY (PYY) and GLP-1 hormone release. This provides persistent satiety signals to the hypothalamus."
  },
  {
    id: "art_3",
    title: "Chronobiology and Focus: Harnessing Ultradian Rhythms",
    category: "productivity",
    readTime: "5 min",
    summary: "Why blocking deep work sessions in 90-minute blocks aligns perfectly with cognitive peak performance phases.",
    content: "Our cognitive performance operates on wave patterns known as Ultradian Rhythms. By integrating 50-minute work sets followed by 10-minute break gaps, the brain restores crucial neurotransmitters."
  }
];

// Initialize local database template mimicking requested tables
const getInitialLocalDb = () => {
  return {
    users: [
      {
        id: "main_user",
        name: "Alex Performance",
        age: 29,
        gender: "Male",
        height: 180,
        weight: 84,
        goalWeight: 78,
        activityLevel: "moderate",
        dietaryPreferences: "Balanced, high-protein",
        allergies: "None",
        medicalConditions: "Slight lower back tension",
        sleepHours: 7,
        dailyRoutine: "Gym mornings, desk work afternoons, reading evenings",
        workSchedule: "9 AM - 6 PM (Remote tech role)",
        fitnessExperience: "intermediate",
        xp: 1250,
        level: 3,
        badges: ["Early Bird", "Deep Worker", "Hydration Hero", "Iron Discipline"],
        streakDays: 8,
        consistencyShields: 2,
      },
    ],
    health_profiles: [
      {
        userId: "main_user",
        healthScore: 84,
        riskFactors: ["Mild screen eye strain", "Sedentary block afternoon fatigue"],
        recommendations: [
          "Perform 5-minute micro-stretches every 90 minutes of desk work.",
          "Keep water flask visible to reach target consumption.",
          "Target protein count 140g - 160g to protect lean mass.",
        ],
      },
    ],
    goals: [
      {
        id: "goal_1",
        title: "Launch Aura Core Software",
        category: "business",
        targetDate: "2026-08-31",
        completed: false,
        milestones: [
          { id: "ms_1", title: "Complete API Architecture", description: "Design express routers and file data-store contracts", status: "completed", weekNumber: 1 },
          { id: "ms_2", title: "Develop Premium Dashboard", description: "Implement responsive metrics, life metrics charts, and quick-add actions", status: "pending", weekNumber: 2 },
          { id: "ms_3", title: "Integrate Gemini AI Briefing & Reflection Engine", description: "Build automated morning briefing and evening accountability panels", status: "pending", weekNumber: 3 },
          { id: "ms_4", title: "Pilot Beta Deployment", description: "Release to early business team advocates for stress evaluation", status: "pending", weekNumber: 4 },
        ],
        weeklyPlans: [
          "Week 1: Core routes structure & basic data-sync layout.",
          "Week 2: Advanced widgets, Pomodoro visual state, and streak charts.",
          "Week 3: LLM prompt architectures, memory optimization, and meal loaders.",
          "Week 4: Polishing transitions, red-team UI audits, and compliance locks.",
        ],
        dailyActions: [
          "Devote 120 minutes of undisturbed focus session.",
          "Perform review on team logs and respond to coaching suggestions.",
          "Log tasks before noon and document reflection summaries.",
        ],
        createdAt: "2026-06-01T08:00:00Z",
      },
    ],
    tasks: [
      { id: "task_1", title: "Complete 15-minute dynamic physical stretch", completed: true, priority: "high", dueDate: "2026-06-10", autoGenerated: false },
      { id: "task_2", title: "Initiate Aura morning system brief", completed: true, priority: "medium", dueDate: "2026-06-10", autoGenerated: true },
    ],
    habit_logs: [
      { id: "h_1", type: "water", value: 4, timestamp: "2026-06-10T11:00:00Z" },
      { id: "h_2", type: "exercise", value: 45, timestamp: "2026-06-10T07:30:00Z" },
    ],
    focus_sessions: [
      { id: "f_1", durationMinutes: 25, timestamp: "2026-06-09T10:15:00Z", mode: "work" },
    ],
    ai_conversations: [
      { sender: "aura", text: "Welcome to Aura. Let's optimize today's performance indices. I'm connected and ready.", timestamp: "2026-06-10T06:45:00Z" },
    ],
    daily_briefings: null,
    daily_reflections: null,
    behavior_predictions: null,
    food_logs: [],
    meal_plans: []
  };
};

const getLocalDb = () => {
  const data = localStorage.getItem("aura_local_db");
  if (!data) {
    const defaultDb = getInitialLocalDb();
    localStorage.setItem("aura_local_db", JSON.stringify(defaultDb));
    return defaultDb;
  }
  return JSON.parse(data);
};

const saveLocalDb = (db: any) => {
  localStorage.setItem("aura_local_db", JSON.stringify(db));
};

const getActiveUser = (db: any) => {
  return db.users[0];
};

const getFallbackCoachingResponse = (message: string, profile: any) => {
  const m = (message || "").toLowerCase();
  if (m.includes("water") || m.includes("drink")) {
    return "Alex, your hydration compliance is vital for cognitive stamina. Grab a glass immediately. I've logged this check.";
  }
  if (m.includes("gym") || m.includes("workout") || m.includes("exercise")) {
    return "Excellent focus on athletic progression. Thriving muscle groups protect your baseline metabolic health index.";
  }
  return `Alex, as your AI strategist Aura, I am tracking your indicators. Let's crush today's priority metrics.`;
};

// Main fetch interceptor
export function setupFetchInterceptor(apiKey: string | undefined) {
  let ai: GoogleGenAI | null = null;
  if (apiKey) {
    try {
      ai = new GoogleGenAI({
        apiKey: apiKey,
        httpOptions: {
          headers: {
            "User-Agent": "aistudio-build",
          },
        },
      });
      console.log("Client-Side Aura AI: Gemini SDK successfully initialized in browser.");
    } catch (err) {
      console.error("Client-Side Aura AI: Initialization error", err);
    }
  }

  const originalFetch = window.fetch;

  const customFetch = async function (input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
    const urlStr = typeof input === "string" ? input : input instanceof URL ? input.toString() : (input as Request).url;

    // Only intercept requests directed to /api
    if (!urlStr.includes("/api/")) {
      return originalFetch(input, init);
    }

    const path = urlStr.split("/api/")[1]?.split("?")[0] || "";
    const method = init?.method?.toUpperCase() || "GET";
    const body = init?.body ? JSON.parse(init.body as string) : null;
    const db = getLocalDb();
    const user = getActiveUser(db);

    console.log(`[Aura Local API] Intercepted: ${method} /api/${path}`);

    let responseData: any = null;
    let status = 200;

    try {
      if (path === "signup") {
        const { id, email, password, name } = body || {};
        let targetUser = db.users.find((u: any) => u.email && email && u.email.toLowerCase() === email.toLowerCase());
        
        if (targetUser) {
          if (id && targetUser.id !== id) {
            targetUser.id = id;
          }
        } else {
          targetUser = {
            id: id || `user_${Date.now()}`,
            email: email,
            password: password,
            name: name || "User",
            age: 28,
            gender: "Male",
            height: 175,
            weight: 72,
            goalWeight: 68,
            activityLevel: "moderate",
            dietaryPreferences: "Balanced",
            allergies: "None",
            medicalConditions: "None",
            sleepHours: 8,
            dailyRoutine: "Productive mornings",
            workSchedule: "9 AM - 5 PM",
            fitnessExperience: "beginner",
            xp: 150,
            level: 1,
            badges: ["First Steps"],
            streakDays: 1,
            consistencyShields: 1
          };
          db.users.push(targetUser);
          db.health_profiles.push({
            userId: targetUser.id,
            healthScore: 80,
            riskFactors: ["Initial staging active"],
            recommendations: ["Log your first action to unlock insights"]
          });
        }
        saveLocalDb(db);
        responseData = { success: true, user: targetUser };

      } else if (path === "signin") {
        const { email, password } = body || {};
        const targetUser = db.users.find(
          (u: any) => u.email && email && u.email.toLowerCase() === email.toLowerCase() && u.password === password
        );
        if (!targetUser) {
          status = 401;
          responseData = { error: "Invalid credentials." };
        } else {
          responseData = { success: true, user: targetUser };
        }

      } else if (path === "profile") {
        const healthProfile = db.health_profiles.find((hp: any) => hp.userId === user?.id) || db.health_profiles[0];
        responseData = {
          user,
          healthProfile,
          family: db.family_accounts?.[0] || { id: "fam_1", familyName: "Performance Family", familyWellnessScore: 82, sharedGoals: ["Hydration run"], members: [] },
          org: db.organizations?.[0] || { id: "corp_1", name: "Alpha Corp Wellness", wellnessScore: 80, activeCampaign: "Water Streak", teams: [] }
        };

      } else if (path === "profile/update") {
        const update = body || {};
        const uIdx = db.users.findIndex((u: any) => u.id === user.id);
        if (uIdx !== -1) {
          db.users[uIdx] = { ...db.users[uIdx], ...update };
          
          // Re-calculate scores
          const weight = Number(db.users[uIdx].weight) || 72;
          const goalWeight = Number(db.users[uIdx].goalWeight) || 68;
          const healthScore = Math.min(95, Math.max(50, 95 - Math.abs(weight - goalWeight) * 2));
          
          let hpIdx = db.health_profiles.findIndex((hp: any) => hp.userId === user.id);
          if (hpIdx === -1) {
            db.health_profiles.push({ userId: user.id, healthScore, riskFactors: [], recommendations: [] });
            hpIdx = db.health_profiles.length - 1;
          }
          db.health_profiles[hpIdx] = {
            userId: user.id,
            healthScore,
            riskFactors: ["Standard performance metric validation"],
            recommendations: [`Maintain calorie guidelines around ${Math.round(weight * 24)} kcal.`]
          };
          saveLocalDb(db);
          responseData = { user: db.users[uIdx], healthProfile: db.health_profiles[hpIdx] };
        } else {
          status = 404;
          responseData = { error: "Profile not found." };
        }

      } else if (path === "goals") {
        if (method === "GET") {
          responseData = db.goals || [];
        } else if (method === "POST") {
          const { title, category, targetDate } = body || {};
          let milestones = [
            { id: `ms_${Date.now()}_1`, title: "Setup Initial Requirements", description: "Establish tools and document baseline indicators", status: "completed" as const, weekNumber: 1 },
            { id: `ms_${Date.now()}_2`, title: "Deploy Prototypes", description: "Assemble early features and seek review", status: "pending" as const, weekNumber: 2 }
          ];
          let weeklyPlans = ["Week 1: Gather baselines", "Week 2: Test prototypes"];
          let dailyActions = ["Dedicate morning focus period"];

          if (ai && title) {
            try {
              const prompt = `You are Aura, elite behavioral coach. Generate a premium structured milestone plan for the goal: "${title}" under category: "${category}" to completion by: "${targetDate}".
              Respond STRICTLY with a valid JSON representation matching this TypeScript schema:
              {
                "milestones": [
                  { "title": string, "description": string, "weekNumber": number }
                ],
                "weeklyPlans": string[],
                "dailyActions": string[]
              }`;

              const response = await ai.models.generateContent({
                model: "gemini-3.5-flash",
                contents: prompt,
                config: {
                  responseMimeType: "application/json",
                  temperature: 0.1,
                },
              });

              if (response.text) {
                const parsed = JSON.parse(response.text.trim());
                if (parsed.milestones) {
                  milestones = parsed.milestones.map((m: any, idx: number) => ({
                    id: `ms_${Date.now()}_${idx}`,
                    title: m.title,
                    description: m.description,
                    status: idx === 0 ? "completed" : "pending",
                    weekNumber: m.weekNumber || (idx + 1)
                  }));
                }
                if (parsed.weeklyPlans) weeklyPlans = parsed.weeklyPlans;
                if (parsed.dailyActions) dailyActions = parsed.dailyActions;
              }
            } catch (err) {
              console.warn("Client Gemini goals error:", err);
            }
          }

          const newGoal = {
            id: `goal_${Date.now()}`,
            title,
            category: category || "other",
            targetDate: targetDate || "2026-12-31",
            completed: false,
            milestones,
            weeklyPlans,
            dailyActions,
            createdAt: new Date().toISOString()
          };
          db.goals.push(newGoal);
          user.xp += 100;
          saveLocalDb(db);
          responseData = db.goals;
        }

      } else if (path.startsWith("goals/") && path.includes("/milestones/") && path.includes("/toggle")) {
        // Toggle goal milestone /api/goals/:goalId/milestones/:milestoneId/toggle
        const parts = path.split("/");
        const goalId = parts[1];
        const milestoneId = parts[3];
        const goal = db.goals.find((g: any) => g.id === goalId);
        if (goal) {
          const ms = goal.milestones.find((m: any) => m.id === milestoneId);
          if (ms) {
            ms.status = ms.status === "completed" ? "pending" : "completed";
            goal.completed = goal.milestones.every((m: any) => m.status === "completed");
            user.xp += 50;
            saveLocalDb(db);
            responseData = db.goals;
          } else {
            status = 404;
          }
        } else {
          status = 404;
        }

      } else if (path.startsWith("goals/milestone/toggle")) {
        const { goalId, milestoneId } = body || {};
        const goal = db.goals.find((g: any) => g.id === goalId);
        if (goal) {
          const ms = goal.milestones.find((m: any) => m.id === milestoneId);
          if (ms) {
            ms.status = ms.status === "completed" ? "pending" : "completed";
            goal.completed = goal.milestones.every((m: any) => m.status === "completed");
            user.xp += 50;
            saveLocalDb(db);
            responseData = db.goals;
          } else {
            status = 404;
          }
        } else {
          status = 404;
        }

      } else if (path.startsWith("goals/")) {
        // DELETE goal or retrieve single: /api/goals/:id
        if (method === "DELETE") {
          const id = path.split("/")[1];
          db.goals = db.goals.filter((g: any) => g.id !== id);
          saveLocalDb(db);
          responseData = db.goals;
        }

      } else if (path === "tasks") {
        if (method === "GET") {
          responseData = db.tasks;
        } else if (method === "POST") {
          const { title, priority, dueDate } = body || {};
          const newTask = {
            id: `task_${Date.now()}`,
            title,
            priority: priority || "medium",
            completed: false,
            dueDate: dueDate || new Date().toISOString().split("T")[0],
            autoGenerated: false
          };
          db.tasks.unshift(newTask);
          saveLocalDb(db);
          responseData = newTask;
        }

      } else if (path === "tasks/toggle") {
        const { id } = body || {};
        const task = db.tasks.find((t: any) => t.id === id);
        if (task) {
          task.completed = !task.completed;
          user.xp += task.completed ? 20 : -20;
          saveLocalDb(db);
          responseData = { task, user };
        } else {
          status = 404;
        }

      } else if (path.startsWith("tasks/")) {
        // DELETE task: /api/tasks/:id
        if (method === "DELETE") {
          const id = path.split("/")[1];
          db.tasks = db.tasks.filter((t: any) => t.id !== id);
          saveLocalDb(db);
          responseData = { success: true };
        }

      } else if (path === "habits" || path === "habits/log") {
        if (method === "GET") {
          responseData = db.habit_logs || [];
        } else if (method === "POST") {
          const { type, value } = body || {};
          const newLog = {
            id: `h_${Date.now()}`,
            type,
            value: Number(value),
            timestamp: new Date().toISOString()
          };
          db.habit_logs.push(newLog);
          user.xp += 15;
          saveLocalDb(db);
          responseData = db.habit_logs;
        }

      } else if (path === "focus" || path === "focus/sessions") {
        responseData = db.focus_sessions || [];

      } else if (path === "focus/log-session") {
        const { durationMinutes, mode } = body || {};
        const newSession = {
          id: `f_${Date.now()}`,
          durationMinutes: Number(durationMinutes || 25),
          mode: mode || "work",
          timestamp: new Date().toISOString()
        };
        db.focus_sessions.push(newSession);
        if (mode === "work") {
          user.xp += Math.round(durationMinutes * 2);
        }
        saveLocalDb(db);
        responseData = db.focus_sessions;

      } else if (path === "nutrition/logs") {
        responseData = db.food_logs || [];

      } else if (path.startsWith("nutrition/logs/")) {
        if (method === "DELETE") {
          const id = path.split("/")[2];
          db.food_logs = db.food_logs.filter((fl: any) => fl.id !== id);
          saveLocalDb(db);
          responseData = db.food_logs;
        }

      } else if (path === "nutrition/meal-plan") {
        responseData = db.meal_plans || [];

      } else if (path === "nutrition/generate-plan") {
        const { daysCount, dietaryPref, targetGoal } = body || {};
        const days = Number(daysCount || 7);
        let generatedPlan = db.meal_plans || [];

        if (ai) {
          try {
            const prompt = `As Aura, elite AI Nutritionist, generate a customized highly nutritious daily meal plan for a ${days}-day cycle.
            Dietary restrictions: "${dietaryPref || 'None'}", goal: "${targetGoal || 'wellness'}".
            Respond STRICTLY with a valid JSON array containing day objects:
            [
              {
                "day": number,
                "meals": {
                  "breakfast": string,
                  "lunch": string,
                  "dinner": string,
                  "snacks": string
                },
                "targets": {
                  "calories": number,
                  "protein": number,
                  "fats": number,
                  "carbs": number,
                  "water": number
                }
              }
            ]`;

            const response = await ai.models.generateContent({
              model: "gemini-3.5-flash",
              contents: prompt,
              config: {
                responseMimeType: "application/json",
                temperature: 0.2
              }
            });

            if (response.text) {
              const parsed = JSON.parse(response.text.trim());
              if (Array.isArray(parsed)) {
                generatedPlan = parsed;
              }
            }
          } catch (err) {
            console.warn("Client Gemini meal plan error:", err);
          }
        }

        if (generatedPlan.length === 0) {
          generatedPlan = Array.from({ length: days }).map((_, i) => ({
            day: i + 1,
            meals: {
              breakfast: "Whole eggs scrambled with avocado",
              lunch: "Grilled salmon and seasoned quinoa",
              dinner: "Seared lean beef steak and vegetables",
              snacks: "Greek yogurt with dynamic protein levels"
            },
            targets: {
              calories: 2000,
              protein: 160,
              fats: 65,
              carbs: 140,
              water: 3.5
            }
          }));
        }

        db.meal_plans = generatedPlan;
        saveLocalDb(db);
        responseData = generatedPlan;

      } else if (path === "nutrition/analyze-photo") {
        const { image } = body || {};
        let result = {
          id: `fl_${Date.now()}`,
          itemName: "Scanned Superfood Dish",
          calories: 520,
          protein: 35,
          carbs: 45,
          fats: 15,
          timestamp: new Date().toISOString()
        };

        if (ai && image) {
          try {
            const pureBase64 = image.replace(/^data:image\/\w+;base64,/, "");
            const response = await ai.models.generateContent({
              model: "gemini-3.5-flash",
              contents: [
                {
                  inlineData: { mimeType: "image/png", data: pureBase64 }
                },
                `Analyze this food picture and estimate macronutrients (itemName, calories, protein, carbs, fats). Respond strictly in JSON.`
              ],
              config: {
                responseMimeType: "application/json",
                temperature: 0.1
              }
            });

            if (response.text) {
              const parsed = JSON.parse(response.text.trim());
              result = {
                id: `fl_${Date.now()}`,
                itemName: parsed.itemName || "Detected Plate",
                calories: Number(parsed.calories || 500),
                protein: Number(parsed.protein || 30),
                carbs: Number(parsed.carbs || 40),
                fats: Number(parsed.fats || 15),
                timestamp: new Date().toISOString()
              };
            }
          } catch (err) {
            console.warn("Client Gemini vision error:", err);
          }
        }

        db.food_logs.unshift(result);
        saveLocalDb(db);
        responseData = db.food_logs;

      } else if (path === "coaching/briefing") {
        const today = new Date().toISOString().split("T")[0];
        let briefing = db.daily_briefings;

        if (!briefing || briefing.date !== today) {
          briefing = {
            id: `b_${Date.now()}`,
            date: today,
            healthScore: 84,
            lifeScore: 80,
            tasksSummary: db.tasks.slice(0, 3).map((t: any) => t.title),
            focusGoal: "Lock in core product milestones early in the day when focus cycles peak.",
            nutritionGoal: "Target 150g protein and 3 liters of pure hydrating water.",
            recs: [
              "Review active milestones and block desk notifications.",
              "Prepare a nutrient-dense mid-day snack to bypass sweet cravings."
            ]
          };

          if (ai) {
            try {
              const activeGoals = db.goals.map((g: any) => g.title).join(", ");
              const response = await ai.models.generateContent({
                model: "gemini-3.5-flash",
                contents: `You are Aura, an elite AI Productivity Coach. Generate a morning advice object (focusGoal, nutritionGoal, recs) based on user goals: ${activeGoals}. Respond strictly in JSON.`,
                config: {
                  responseMimeType: "application/json",
                  temperature: 0.3
                }
              });

              if (response.text) {
                const parsed = JSON.parse(response.text.trim());
                briefing = {
                  id: `b_${Date.now()}`,
                  date: today,
                  healthScore: 84,
                  lifeScore: 85,
                  tasksSummary: db.tasks.slice(0, 3).map((t: any) => t.title),
                  focusGoal: parsed.focusGoal,
                  nutritionGoal: parsed.nutritionGoal,
                  recs: parsed.recs
                };
              }
            } catch (err) {
              console.warn("Client Gemini briefings error:", err);
            }
          }
          db.daily_briefings = briefing;
          saveLocalDb(db);
        }
        responseData = briefing;

      } else if (path === "coaching/reflection") {
        const today = new Date().toISOString().split("T")[0];
        let reflection = db.daily_reflections;

        if (!reflection || reflection.date !== today) {
          const completedCount = db.tasks.filter((t: any) => t.completed).length;
          const waterGlasses = db.habit_logs.filter((h: any) => h.type === "water").reduce((acc: number, curr: any) => acc + curr.value, 0);

          reflection = {
            id: `r_${Date.now()}`,
            date: today,
            tasksCompleted: completedCount,
            focusSessionsCompleted: db.focus_sessions.length,
            waterIntake: waterGlasses,
            nutritionCompliance: "good",
            habitCompletionRate: Math.round((completedCount / Math.max(1, db.tasks.length)) * 100),
            recsForTomorrow: [
              "Log priorities preceding the core work blocks.",
              "Secure hydration reservoirs on your active desk."
            ]
          };

          if (ai) {
            try {
              const response = await ai.models.generateContent({
                model: "gemini-3.5-flash",
                contents: `Analyze performance metrics (tasks completed: ${completedCount}, water logged: ${waterGlasses}). Output nutritionCompliance ('poor' | 'fair' | 'good' | 'perfect') and recsForTomorrow array. Respond strictly in JSON.`,
                config: {
                  responseMimeType: "application/json",
                  temperature: 0.3
                }
              });

              if (response.text) {
                const parsed = JSON.parse(response.text.trim());
                reflection = {
                  id: `r_${Date.now()}`,
                  date: today,
                  tasksCompleted: completedCount,
                  focusSessionsCompleted: db.focus_sessions.length,
                  waterIntake: waterGlasses,
                  nutritionCompliance: parsed.nutritionCompliance || "good",
                  habitCompletionRate: Math.round((completedCount / Math.max(1, db.tasks.length)) * 100),
                  recsForTomorrow: parsed.recsForTomorrow || []
                };
              }
            } catch (err) {
              console.warn("Client Gemini reflections error:", err);
            }
          }
          db.daily_reflections = reflection;
          saveLocalDb(db);
        }
        responseData = reflection;

      } else if (path === "coaching/predict-behavior") {
        const today = new Date().toISOString().split("T")[0];
        let prediction = db.behavior_predictions;

        if (!prediction || prediction.date !== today) {
          prediction = {
            date: today,
            burnoutRisk: "low",
            missedWorkoutProb: 15,
            productivityCrashProb: 20,
            junkFoodCravingRisk: "moderate",
            warningMessage: "Prolonged desk work creates late-day cognitive fogs.",
            interventions: [
              "Introduce a 5-minute physical reset stretch every 90 minutes of desk sessions.",
              "Prepare a healthy snack block before afternoon craving periods."
            ]
          };

          if (ai) {
            try {
              const goalTitle = db.goals[0]?.title || "Consistency";
              const response = await ai.models.generateContent({
                model: "gemini-3.5-flash",
                contents: `Predict performance slumps for goal: "${goalTitle}". Return JSON: { burnoutRisk: 'low'|'moderate'|'high', missedWorkoutProb: 0-100, productivityCrashProb: 0-100, junkFoodCravingRisk: 'low'|'moderate'|'high', warningMessage: string, interventions: string[] }. Respond strictly in JSON.`,
                config: {
                  responseMimeType: "application/json",
                  temperature: 0.1
                }
              });

              if (response.text) {
                const parsed = JSON.parse(response.text.trim());
                prediction = { ...parsed, date: today };
              }
            } catch (err) {
              console.warn("Client Gemini behavior predictions error:", err);
            }
          }
          db.behavior_predictions = prediction;
          saveLocalDb(db);
        }
        responseData = prediction;

      } else if (path === "coaching/chat") {
        if (method === "GET") {
          responseData = db.ai_conversations || [];
        } else if (method === "POST") {
          const { message } = body || {};
          const userMsg = { sender: "user" as const, text: message, timestamp: new Date().toISOString() };
          db.ai_conversations.push(userMsg);

          let replyText = "";
          if (ai) {
            try {
              const chatHistory = db.ai_conversations.slice(-8).map((c: any) => `${c.sender}: ${c.text}`).join("\n");
              const systemPrompt = `You are Aura, an elite AI Performance Coach and behavioral psychologist. Speak as an executive strategist. Keep entries brief, highly tactical, actionable, and tailored to Alex. Avoid generic templates, limit output to 2-3 concise paragraphs.`;
              
              const response = await ai.models.generateContent({
                model: "gemini-3.5-flash",
                contents: `Dialogue History:\n${chatHistory}\n\nLatest Alexa input:\nuser: ${message}\n\nAura response:`,
                config: {
                  systemInstruction: systemPrompt,
                  temperature: 0.7
                }
              });
              replyText = response.text || getFallbackCoachingResponse(message, user);
            } catch (err) {
              console.warn("Client Gemini chat error:", err);
              replyText = getFallbackCoachingResponse(message, user);
            }
          } else {
            replyText = getFallbackCoachingResponse(message, user);
          }

          const auraMsg = { sender: "aura" as const, text: replyText, timestamp: new Date().toISOString() };
          db.ai_conversations.push(auraMsg);
          saveLocalDb(db);
          responseData = db.ai_conversations;
        }

      } else if (path === "articles") {
        responseData = DEFAULT_ARTICLES;

      } else if (path === "gamification") {
        responseData = {
          badges: ["Early Bird", "Deep Worker", "Hydration Hero", "Iron Discipline", "Pro Planner", "Burnout Resilient"],
          weeklyChallenge: {
            title: "Performance Run 100",
            description: "Maintain consecutive logs and water quotas for absolute streak scores.",
            xpReward: 500,
            badgeReward: "Zen Master",
            participants: 1200
          }
        };

      } else {
        // Fallback or unhandled api endpoint
        return originalFetch(input, init);
      }

      // Return emulated Response object
      return new Response(JSON.stringify(responseData), {
        status,
        headers: { "Content-Type": "application/json" }
      });

    } catch (err: any) {
      console.error(`[Aura Local API Error] ${path}:`, err);
      return new Response(JSON.stringify({ error: err.message || "Endpoint error" }), {
        status: 500,
        headers: { "Content-Type": "application/json" }
      });
    }
  };

  try {
    Object.defineProperty(window, "fetch", {
      value: customFetch,
      configurable: true,
      writable: true,
      enumerable: true
    });
  } catch (err) {
    console.warn("[Aura] Object.defineProperty(window, 'fetch') failed, falling back to direct assignment", err);
    try {
      (window as any).fetch = customFetch;
    } catch (err2) {
      console.error("[Aura] Critical: Could not intercept fetch on window object", err2);
    }
  }
}

export async function initClientBackend() {
  const apiKey = (import.meta as any).env.VITE_GEMINI_API_KEY;
  const isVercel = window.location.hostname !== "localhost" && window.location.hostname !== "127.0.0.1";
  
  // Probe if our Express api server is alive
  let isApiServerAlive = false;
  try {
    const res = await fetch("/api/profile", { method: "GET" });
    if (res.ok) {
      isApiServerAlive = true;
    }
  } catch (err) {
    isApiServerAlive = false;
  }
  
  if (!isApiServerAlive || isVercel) {
    console.log("Client-Side Emulator mode activated due to Vercel/inactive server.");
    setupFetchInterceptor(apiKey);
  } else {
    console.log("Server is alive; running standard server-side APIs.");
  }
}

