/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface UserProfile {
  id: string;
  name: string;
  age: number;
  gender: string;
  height: number; // in cm
  weight: number; // in kg
  goalWeight: number; // in kg
  activityLevel: string; // 'sedentary' | 'light' | 'moderate' | 'very'
  dietaryPreferences: string;
  allergies: string;
  medicalConditions: string;
  sleepHours: number;
  dailyRoutine: string;
  workSchedule: string;
  fitnessExperience: string; // 'beginner' | 'intermediate' | 'advanced'
  
  // Gamification properties
  xp: number;
  level: number;
  badges: string[];
  streakDays: number;
  consistencyShields: number;
}

export interface GoalMilestone {
  id: string;
  title: string;
  description: string;
  status: 'pending' | 'completed';
  weekNumber: number;
}

export interface Goal {
  id: string;
  title: string; // e.g. "Launch Startup"
  category: string; // 'fitness' | 'business' | 'learning' | 'other'
  targetDate: string;
  completed: boolean;
  milestones: GoalMilestone[];
  weeklyPlans: string[];
  dailyActions: string[];
  createdAt: string;
}

export interface Task {
  id: string;
  title: string;
  completed: boolean;
  priority: 'low' | 'medium' | 'high';
  dueDate: string;
  autoGenerated: boolean;
}

export interface HabitLog {
  id: string;
  type: 'water' | 'exercise' | 'sleep' | 'reading' | 'meditation' | 'walking' | 'journaling';
  value: number; // generic representing glass, minutes, hours, or simple 1 (done)
  timestamp: string;
}

export interface FocusSession {
  id: string;
  durationMinutes: number;
  timestamp: string;
  mode: 'work' | 'short_break' | 'long_break';
}

export interface DailyBriefing {
  id: string;
  date: string;
  healthScore: number;
  lifeScore: number;
  tasksSummary: string[];
  focusGoal: string;
  nutritionGoal: string;
  recs: string[];
  isStandby?: boolean;
}

export interface DailyReflection {
  id: string;
  date: string;
  tasksCompleted: number;
  focusSessionsCompleted: number;
  waterIntake: number;
  nutritionCompliance: 'poor' | 'fair' | 'good' | 'perfect';
  habitCompletionRate: number;
  recsForTomorrow: string[];
  isStandby?: boolean;
}

export interface BehaviorPrediction {
  burnoutRisk: 'low' | 'moderate' | 'high';
  missedWorkoutProb: number; // percentage
  productivityCrashProb: number; // percentage
  junkFoodCravingRisk: 'low' | 'moderate' | 'high';
  warningMessage: string;
  interventions: string[];
  date?: string;
  isStandby?: boolean;
}

export interface FamilyMember {
  id: string;
  name: string;
  role: 'parent' | 'child' | 'spouse';
  lifeScore: number;
}

export interface FamilyAccount {
  id: string;
  familyName: string;
  members: FamilyMember[];
  sharedGoals: string[];
  familyWellnessScore: number;
}

export interface TeamMember {
  id: string;
  name: string;
  burnoutRisk: 'low' | 'medium' | 'high';
  productivityScore: number;
}

export interface BusinessTeam {
  id: string;
  name: string;
  members: TeamMember[];
  burnoutScale: number; // 0-100 (high is bad)
  productivityScale: number; // 0-100 (high is good)
  engagementScore: number; // 0-100
}

export interface MealPlanDay {
  day: number;
  meals: {
    breakfast: string;
    lunch: string;
    dinner: string;
    snacks: string;
  };
  targets: {
    calories: number;
    protein: number;
    fats: number;
    carbs: number;
    water: number;
  };
}

export interface FoodLog {
  id: string;
  itemName: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  timestamp: string;
}

export interface Message {
  sender: 'user' | 'aura';
  text: string;
  timestamp: string;
}

export interface Article {
  id: string;
  title: string;
  category: string;
  readTime: string;
  summary: string;
  content: string;
}
